name: daily-cron
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Scrape Data and Save to postgres db
        run: |
          python scraper.py
